[2024-08-05T20:57:51.128+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T20:57:51.215+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jobs_etl.Loading_Data_to_DataBase scheduled__2024-08-04T18:00:00+00:00 [queued]>
[2024-08-05T20:57:51.238+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jobs_etl.Loading_Data_to_DataBase scheduled__2024-08-04T18:00:00+00:00 [queued]>
[2024-08-05T20:57:51.239+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-05T20:57:51.275+0100] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Loading_Data_to_DataBase> on 2024-08-04 18:00:00+00:00
[2024-08-05T20:57:51.295+0100] {standard_task_runner.py:63} INFO - Started process 594387 to run task
[2024-08-05T20:57:51.302+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'jobs_etl', 'Loading_Data_to_DataBase', 'scheduled__2024-08-04T18:00:00+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/jobs_etl.py', '--cfg-path', '/tmp/tmpe48roqrs']
[2024-08-05T20:57:51.307+0100] {standard_task_runner.py:91} INFO - Job 301: Subtask Loading_Data_to_DataBase
[2024-08-05T20:57:51.444+0100] {task_command.py:426} INFO - Running <TaskInstance: jobs_etl.Loading_Data_to_DataBase scheduled__2024-08-04T18:00:00+00:00 [running]> on host huser
[2024-08-05T20:57:51.654+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hassounibarka@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='jobs_etl' AIRFLOW_CTX_TASK_ID='Loading_Data_to_DataBase' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-04T18:00:00+00:00'
[2024-08-05T20:57:51.656+0100] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T20:57:51.764+0100] {logging_mixin.py:188} INFO - DB connected successfully
[2024-08-05T20:57:52.421+0100] {logging_mixin.py:188} INFO - Data inserted successfully from CSV
[2024-08-05T20:57:52.422+0100] {python.py:237} INFO - Done. Returned value was: None
[2024-08-05T20:57:52.423+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T20:57:52.464+0100] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=jobs_etl, task_id=Loading_Data_to_DataBase, run_id=scheduled__2024-08-04T18:00:00+00:00, execution_date=20240804T180000, start_date=20240805T195751, end_date=20240805T195752
[2024-08-05T20:57:52.540+0100] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-05T20:57:52.591+0100] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-05T20:57:52.593+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
