[2024-09-08T22:53:17.247+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-08T22:53:17.289+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jobs_etl.Loading_Data_to_DataBase scheduled__2024-09-07T18:00:00+00:00 [queued]>
[2024-09-08T22:53:17.297+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jobs_etl.Loading_Data_to_DataBase scheduled__2024-09-07T18:00:00+00:00 [queued]>
[2024-09-08T22:53:17.297+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-08T22:53:17.309+0100] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Loading_Data_to_DataBase> on 2024-09-07 18:00:00+00:00
[2024-09-08T22:53:17.324+0100] {standard_task_runner.py:63} INFO - Started process 212639 to run task
[2024-09-08T22:53:17.328+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'jobs_etl', 'Loading_Data_to_DataBase', 'scheduled__2024-09-07T18:00:00+00:00', '--job-id', '438', '--raw', '--subdir', 'DAGS_FOLDER/jobs_etl.py', '--cfg-path', '/tmp/tmpe41dg63r']
[2024-09-08T22:53:17.331+0100] {standard_task_runner.py:91} INFO - Job 438: Subtask Loading_Data_to_DataBase
[2024-09-08T22:53:17.414+0100] {task_command.py:426} INFO - Running <TaskInstance: jobs_etl.Loading_Data_to_DataBase scheduled__2024-09-07T18:00:00+00:00 [running]> on host huser
[2024-09-08T22:53:17.536+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hassounibarka@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='jobs_etl' AIRFLOW_CTX_TASK_ID='Loading_Data_to_DataBase' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T18:00:00+00:00'
[2024-09-08T22:53:17.537+0100] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-08T22:53:17.588+0100] {logging_mixin.py:188} INFO - DB connected successfully
[2024-09-08T22:53:17.660+0100] {logging_mixin.py:188} INFO - Data inserted successfully from CSV
[2024-09-08T22:53:17.661+0100] {python.py:237} INFO - Done. Returned value was: None
[2024-09-08T22:53:17.662+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-08T22:53:17.680+0100] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=jobs_etl, task_id=Loading_Data_to_DataBase, run_id=scheduled__2024-09-07T18:00:00+00:00, execution_date=20240907T180000, start_date=20240908T215317, end_date=20240908T215317
[2024-09-08T22:53:17.711+0100] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-08T22:53:17.736+0100] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-08T22:53:17.737+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
