[2024-09-08T20:03:00.274+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-08T20:03:00.321+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jobs_etl.glassdoor_scraper scheduled__2024-09-07T18:00:00+00:00 [queued]>
[2024-09-08T20:03:00.332+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jobs_etl.glassdoor_scraper scheduled__2024-09-07T18:00:00+00:00 [queued]>
[2024-09-08T20:03:00.333+0100] {taskinstance.py:2306} INFO - Starting attempt 7 of 8
[2024-09-08T20:03:00.347+0100] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): glassdoor_scraper> on 2024-09-07 18:00:00+00:00
[2024-09-08T20:03:00.369+0100] {standard_task_runner.py:63} INFO - Started process 202420 to run task
[2024-09-08T20:03:00.375+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'jobs_etl', 'glassdoor_scraper', 'scheduled__2024-09-07T18:00:00+00:00', '--job-id', '431', '--raw', '--subdir', 'DAGS_FOLDER/jobs_etl.py', '--cfg-path', '/tmp/tmp0sw1tjmw']
[2024-09-08T20:03:00.379+0100] {standard_task_runner.py:91} INFO - Job 431: Subtask glassdoor_scraper
[2024-09-08T20:03:00.491+0100] {task_command.py:426} INFO - Running <TaskInstance: jobs_etl.glassdoor_scraper scheduled__2024-09-07T18:00:00+00:00 [running]> on host huser
[2024-09-08T20:03:00.674+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hassounibarka@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='jobs_etl' AIRFLOW_CTX_TASK_ID='glassdoor_scraper' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T18:00:00+00:00'
[2024-09-08T20:03:00.677+0100] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-08T20:03:20.029+0100] {logging_mixin.py:188} INFO - Keyword error
[2024-09-08T20:03:21.117+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-08T20:03:21.118+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/huser/airflow_workspace/airflow/dags/jobs_etl.py", line 31, in get_glassdoor_data
    df = glassdoor_scraper.get_datas(Keywords)
  File "/home/huser/airflow_workspace/airflow/dags/Jobs/GlassdoorScraper.py", line 143, in get_datas
    links = get_links(key)
  File "/home/huser/airflow_workspace/airflow/dags/Jobs/GlassdoorScraper.py", line 69, in get_links
    return Links
UnboundLocalError: local variable 'Links' referenced before assignment
[2024-09-08T20:03:21.178+0100] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=jobs_etl, task_id=glassdoor_scraper, run_id=scheduled__2024-09-07T18:00:00+00:00, execution_date=20240907T180000, start_date=20240908T190300, end_date=20240908T190321
[2024-09-08T20:03:21.217+0100] {standard_task_runner.py:110} ERROR - Failed to execute job 431 for task glassdoor_scraper (local variable 'Links' referenced before assignment; 202420)
[2024-09-08T20:03:21.273+0100] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-08T20:03:21.377+0100] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-08T20:03:21.381+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
