[2024-08-01T21:20:23.482+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-01T21:20:23.517+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jobs_etl.Loading_Data_to_DataBase scheduled__2024-07-31T18:00:00+00:00 [queued]>
[2024-08-01T21:20:23.525+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jobs_etl.Loading_Data_to_DataBase scheduled__2024-07-31T18:00:00+00:00 [queued]>
[2024-08-01T21:20:23.525+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-01T21:20:23.537+0100] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Loading_Data_to_DataBase> on 2024-07-31 18:00:00+00:00
[2024-08-01T21:20:23.548+0100] {standard_task_runner.py:63} INFO - Started process 366584 to run task
[2024-08-01T21:20:23.552+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'jobs_etl', 'Loading_Data_to_DataBase', 'scheduled__2024-07-31T18:00:00+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/jobs_etl.py', '--cfg-path', '/tmp/tmpf5wizfh1']
[2024-08-01T21:20:23.555+0100] {standard_task_runner.py:91} INFO - Job 270: Subtask Loading_Data_to_DataBase
[2024-08-01T21:20:23.632+0100] {task_command.py:426} INFO - Running <TaskInstance: jobs_etl.Loading_Data_to_DataBase scheduled__2024-07-31T18:00:00+00:00 [running]> on host huser
[2024-08-01T21:20:23.752+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hassounibarka@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='jobs_etl' AIRFLOW_CTX_TASK_ID='Loading_Data_to_DataBase' AIRFLOW_CTX_EXECUTION_DATE='2024-07-31T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-31T18:00:00+00:00'
[2024-08-01T21:20:23.753+0100] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-01T21:20:23.816+0100] {logging_mixin.py:188} INFO - DB connected successfully
[2024-08-01T21:20:24.155+0100] {logging_mixin.py:188} INFO - Data inserted successfully from CSV
[2024-08-01T21:20:24.156+0100] {python.py:237} INFO - Done. Returned value was: None
[2024-08-01T21:20:24.156+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-01T21:20:24.172+0100] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=jobs_etl, task_id=Loading_Data_to_DataBase, run_id=scheduled__2024-07-31T18:00:00+00:00, execution_date=20240731T180000, start_date=20240801T202023, end_date=20240801T202024
[2024-08-01T21:20:24.215+0100] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-01T21:20:24.240+0100] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-01T21:20:24.242+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
